### ISSUE TITLE
Bad entity escaping on the generated webpage

### ISSUE THREAD

**Issue by milleniumbug** [LoungeCPP/loungesome-cpp#15]
Currently `<chrono>` is displayed as `&lt;chrono&gt;` on the site

**Comment by nabijaczleweli** [comment]
blergh

**Comment by nabijaczleweli** [comment]
I've traced the issue down to `www.willpeavy.com/minifier` replacing all instances of `&lt;` and `&gt;` with `&amp;lt;` and `&amp;gt;`
