### ISSUE TITLE
There is no whitespace between "build passing" and "license CC0" on the web page

### ISSUE THREAD

**Issue by no-longer-on-githu-b** [LoungeCPP/loungesome-cpp#18]

**Comment by nabijaczleweli** [comment]
Well then correct it!

**Comment by skorezore** [comment]
I suck.

**Comment by nabijaczleweli** [comment]
It works, so you don't

**Comment by ghost** [comment]
why don't you guys contribute candidates libs instead of bikeshedding? POCO is still in the wait list

**Comment by no-longer-on-githu-b** [comment]
because that's incredibly boring

playing video games is much more fun

**Comment by Morwenn** [comment]
I guess I've already mentioned every library I ever used, and even a few more. I can't really help much more.

**Comment by milleniumbug** [comment]
Dunno, there are some libraries in the "wait list", but I'm not pushing them until I see another vote on them.

Otherwise I don't want to nominate libraries which I didn't even use, that would be missing the point of this list.

**Comment by nabijaczleweli** [comment]
@milleniumbug [_cough_](https://github.com/LoungeCPP/loungesome-cpp/issues/13#issuecomment-187389006)
