### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by ghost** [LoungeCPP/loungesome-cpp#19]
@milleniumbug drew to our attention that we never really talked about what the criteria for acceptance should be.

I propose that any nominated item with two or more votes (as in, upvotes - downvotes) during at least 24h be put into the list. 

What do you guys think?

We can increase the vote count if we get more contributors, or if non-loungers start voting here.

**Comment by no-longer-on-githu-b** [comment]
What are the criteria for accepting these acceptance criteria?

**Comment by ghost** [comment]
Majority vote among the 5 first contributors of the list.
The acceptance criterion for accepting the acceptance criteria of new acceptance criteria has been unilaterally decided by me because it was my idea.

**Comment by ghost** [comment]
@nabijaczleweli thanks for the labelling, but please share your opinion as well

**Comment by Morwenn** [comment]
I'm ok with that as long as there aren't too many contributors. Eventually we'll have to change the thresholds.

**Comment by nabijaczleweli** [comment]
v0v, really. 2 votes sum makes sense for now.

**Comment by ghost** [comment]
Fine, then it's settled. For now.
