### ISSUE TITLE
Use GFM for webpage generation

### ISSUE THREAD

**Issue by nabijaczleweli** [LoungeCPP/loungesome-cpp#6]
Just calling `markdown` makes it look shit

**Comment by nabijaczleweli** [comment]
Done.

**Comment by nabijaczleweli** [comment]
Yo, @LoungeCPP/lounge, what'cha think about the new design?
It's a non-bad (although white) design I pulled off somewhere, trying to mimic GH's.

It's deployed [here](http://loungecpp.github.io/loungesome-cpp) (should we link to that [here](https://github.com/LoungeCPP/loungesome-cpp/blob/f32def035bf7dea01a85479ba9c68064af70abc9/README.md#loungesome-cpp--)?).

**Comment by no-longer-on-githu-b** [comment]
Looks fine. Make it responsive.

**Comment by nabijaczleweli** [comment]
Closed via https://github.com/LoungeCPP/loungesome-cpp/commit/ec7341b201cec5953fc5f35060b2951448a4207f .. https://github.com/LoungeCPP/loungesome-cpp/commit/4a5b32ce478cdc5ff9a8a362324ef8b287afd6a1.
