### ISSUE TITLE
Add HTML <head> metadata

### ISSUE THREAD

**Issue by nabijaczleweli** [LoungeCPP/loungesome-cpp#7]
Currently just a `<title>` and a lame one at that.

**Comment by nabijaczleweli** [comment]
Should also compact the thing before deployment

**Comment by nabijaczleweli** [comment]
Yo @kbok, what should the `<title>` be?
I was thinking about something along these lines:

> loungesome-cpp — a list of actually good C++ libraries

**Comment by ghost** [comment]
"actually awesome"?

**Comment by Morwenn** [comment]
Er, the problem is that we'll be the first ones to consider that some frameworks, libraries and tools are not awesome but still worth mentioning.

**Comment by ghost** [comment]
Yeah - it's C++. Most of the ecosystem is about making concessions. Let's stick with "actually good" @nabijaczleweli

**Comment by nabijaczleweli** [comment]
Any more tags/keywords, @kbok?

**Comment by ghost** [comment]
It would probably be nice to mention awesome, but maybe in the page body. your title sounds fine imo.
