### ISSUE TITLE
Favicon for webpage

### ISSUE THREAD

**Issue by nabijaczleweli** [LoungeCPP/loungesome-cpp#8]
@kbok, should we just use the http://loungecpp.net favicon or...?

**Comment by ghost** [comment]
let's hold a contest

**Comment by ghost** [comment]
Maybe something based on the awesome logo (https://github.com/sindresorhus/awesome), if the conditions/the author agrees

**Comment by nabijaczleweli** [comment]
@kbok How about ![logo](https://cloud.githubusercontent.com/assets/6709544/12519497/7aac3962-c13f-11e5-85ef-078e40d17d72.png)?

**Comment by nabijaczleweli** [comment]
Or ![logo_nocxx](https://cloud.githubusercontent.com/assets/6709544/12519510/a1887a1e-c13f-11e5-89c0-61d6be9f2748.png)?

**Comment by Morwenn** [comment]
I don't really like both logos at once :/

**Comment by nabijaczleweli** [comment]
So just ![logo](https://raw.githubusercontent.com/LoungeCPP/loungecpp.net/gh-pages/assets/img/logo.png)?

**Comment by Morwenn** [comment]
I'd probably go with that one: the mustache sofa is alreay awesome.
